"""
Django settings for API project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# File storage backend toggle:
# - False => local filesystem storage (no django-storages dependency required)
# - True  => AWS S3 storage (requires django-storages/boto3)
USE_S3 = config('USE_S3', default=False, cast=bool)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-rfwr9@$tm$bp^-x%v%n$j3dz%)^aenhm%2hl-ds6oifkl2a!+a')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Allowed hosts - includes production API domain and localhost for development
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,devapi.wedesignz.com').split(',')

# CSRF Trusted Origins - origins that are trusted for CSRF checks
# This is needed for cross-origin requests from frontend applications
CSRF_TRUSTED_ORIGINS = [
    # Production domains
    "https://wedesignz.com",
    "https://www.wedesignz.com",
    "https://admin.wedesignz.com",
    
    # Development domains
    "https://webapp.wedesignz.com",
    "https://adminwebapp.wedesignz.com",
    
    # Local development domains
    "http://localhost:5000",
    "http://127.0.0.1:5000",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5001",
    "http://127.0.0.1:5001",
    "http://localhost:5002",
    "http://127.0.0.1:5002",
]

# Allow CSRF trusted origins from environment variable
CSRF_TRUSTED_ORIGINS_STR = config('CSRF_TRUSTED_ORIGINS', default='')
if CSRF_TRUSTED_ORIGINS_STR:
    additional_origins = [origin.strip() for origin in CSRF_TRUSTED_ORIGINS_STR.split(',') if origin.strip()]
    CSRF_TRUSTED_ORIGINS.extend(additional_origins)


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Jazzmin admin theme
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # CORS headers for cross-origin requests
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_yasg',  # Swagger documentation
    
    # Celery apps
    'django_celery_beat',  # Celery Beat for periodic tasks
    'django_celery_results',  # Celery Results backend
    
    # Custom apps
    'common',  # Common utilities, signals, and cron jobs
    'Authentication',
    'CoreAdmin',  # Core Admin Panel
    'AdminAnalytics',  # Admin Analytics and Reports
    'Accounts',
    'Catalog',
    'Coupons',
    'CustomRequests',
    'Feedback',
    'MediaFiles',
    'Orders',
    'Plans',
    'Profiles',
    'Razorpay',
    'Wallet',
]

if USE_S3:
    INSTALLED_APPS.append('storages')  # AWS S3 storage backend

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware - must be before CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'CoreAdmin.middleware.ModeratorRestrictionMiddleware',
    'CoreAdmin.middleware.AdminActivityLoggingMiddleware',
    'common.error_handler.ErrorHandlerMiddleware',  # Error logging middleware - should be last
]

ROOT_URLCONF = 'API.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'API.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.postgresql'),
        'NAME': config('DB_NAME', default='wedesignz_db'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# Media files configuration
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# For Development
# STATIC_URL = '/static/'
# STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles/')
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# For Production
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# Only include staticfiles directory if it exists
staticfiles_dir = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    staticfiles_dir,
] if os.path.exists(staticfiles_dir) else []
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

if USE_S3:
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='ap-south-1')
    AWS_S3_SIGNATURE_VERSION = config('AWS_S3_SIGNATURE_VERSION', default='s3v4')

    # File URLs and S3 locations
    AWS_S3_CUSTOM_DOMAIN = config('AWS_S3_CUSTOM_DOMAIN', default='')
    AWS_MEDIA_LOCATION = config('AWS_MEDIA_LOCATION', default='media')
    AWS_PUBLIC_MEDIA_LOCATION = config('AWS_PUBLIC_MEDIA_LOCATION', default='media/public')
    AWS_PRIVATE_MEDIA_LOCATION = config('AWS_PRIVATE_MEDIA_LOCATION', default='media/private')
    AWS_PRIVATE_URL_EXPIRE = config('AWS_PRIVATE_URL_EXPIRE', default=3600, cast=int)
    AWS_PRIVATE_PATH_MARKERS = [
        marker.strip()
        for marker in config(
            'AWS_PRIVATE_PATH_MARKERS',
            default='/private/',
        ).split(',')
        if marker.strip()
    ]

    # Backward-compatible aliases for existing code/env usage.
    AWS_LOCATION = AWS_MEDIA_LOCATION
    AWS_QUERYSTRING_AUTH = config('AWS_QUERYSTRING_AUTH', default=False, cast=bool)
    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = False

    STORAGES = {
        'default': {
            # Safe default for unspecified fields.
            'BACKEND': 'common.storages.PrivateMediaStorage',
        },
        'public_media': {
            'BACKEND': 'common.storages.PublicMediaStorage',
        },
        'private_media': {
            'BACKEND': 'common.storages.PrivateMediaStorage',
        },
        'mixed_media': {
            'BACKEND': 'common.storages.MixedMediaStorage',
        },
        'legacy_s3': {
            'BACKEND': 'storages.backends.s3.S3Storage',
            'OPTIONS': {
                'bucket_name': AWS_STORAGE_BUCKET_NAME,
                'region_name': AWS_S3_REGION_NAME,
                'default_acl': AWS_DEFAULT_ACL,
                'querystring_auth': AWS_QUERYSTRING_AUTH,
                'file_overwrite': AWS_S3_FILE_OVERWRITE,
                'location': AWS_MEDIA_LOCATION,
                'custom_domain': AWS_S3_CUSTOM_DOMAIN or None,
            },
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }

    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_MEDIA_LOCATION}/'
    else:
        MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/{AWS_MEDIA_LOCATION}/'
else:
    MEDIA_URL = '/media/'

# File Upload Size Limits (1GB = 1073741824 bytes)
DATA_UPLOAD_MAX_MEMORY_SIZE = 1073741824  # 1GB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # Increase limit for admin list views with many items
FILE_UPLOAD_MAX_MEMORY_SIZE = 1073741824  # 1GB

# Email Configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='')

# Site Domain (for building absolute URLs)
SITE_DOMAIN = config('SITE_DOMAIN', default='wedesignz.com')  # Main website domain (for design links)
MEDIA_DOMAIN = config('MEDIA_DOMAIN', default='devapi.wedesignz.com')  # Media files domain (where images are hosted)
INSTAGRAM_MEDIA_DOMAIN = config('INSTAGRAM_MEDIA_DOMAIN', default=None)  # Publicly accessible domain for Instagram posts (if None, uses MEDIA_DOMAIN)
ENVIRONMENT = config('ENVIRONMENT', default='production').lower()  # development | production (used e.g. for local Instagram tunnel instructions)
ADMIN_WEBAPP_URL = config('ADMIN_WEBAPP_URL', default='https://admin.wedesignz.com')  # Admin webapp URL (for redirects)

# Pinterest Integration Settings
PINTEREST_APP_ID = config('PINTEREST_APP_ID', default='')
PINTEREST_APP_SECRET = config('PINTEREST_APP_SECRET', default='')
PINTEREST_REDIRECT_URI = config('PINTEREST_REDIRECT_URI', default='https://wedesignz.com/api/pinterest/callback')
PINTEREST_USE_SANDBOX = config('PINTEREST_USE_SANDBOX', default='True', cast=bool)  # Use sandbox for trial access
# Note: Access token and board ID are stored in PinterestIntegration model (database)
# These env vars are fallbacks for initial setup
PINTEREST_ACCESS_TOKEN = config('PINTEREST_ACCESS_TOKEN', default='')
PINTEREST_BOARD_ID = config('PINTEREST_BOARD_ID', default='')
PINTEREST_ENABLED = config('PINTEREST_ENABLED', default='False', cast=bool)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Jazzmin Admin Theme Configuration
# https://github.com/farridav/django-jazzmin
JAZZMIN_SETTINGS = {
    # Title on the login screen (19 chars max)
    "site_title": "WeDesignz Admin",
    
    # Title on the brand (19 chars max)
    "site_header": "WeDesignz",
    
    # Title on the brand when screen is at least 992px wide
    "site_brand": "WeDesignz Administration",
    
    # Logo to use for your site, must be present in static files, used for brand on top left
    # "site_logo": "books/img/logo.png",
    
    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    # "login_logo": None,
    
    # Logo to use for login form in dark themes (defaults to login_logo)
    # "login_logo_dark": None,
    
    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-circle",
    
    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    # "site_icon": None,
    
    # Welcome text on the login screen
    "welcome_sign": "Welcome to WeDesignz Administration",
    
    # Copyright on the footer
    "copyright": "WeDesignz",
    
    # The model admin to search from the search bar, search bar omitted if excluded
    "search_model": ["auth.User", "auth.Group"],
    
    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
    "user_avatar": None,
    
    ############
    # Top Menu #
    ############
    
    # Links to put along the top menu
    "topmenu_links": [
        # Url that gets reversed (Permissions can be added)
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        
        # external url that opens in a new window (Permissions can be added)
        # {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        
        # model admin to link to (Permissions checked against model)
        # {"model": "auth.User"},
        
        # App with dropdown menu to all its models pages (Permissions checked against models)
        # {"app": "books"},
    ],
    
    #############
    # User Menu #
    #############
    
    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    "usermenu_links": [
        # {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        # {"model": "auth.user"}
    ],
    
    #############
    # Side Menu #
    #############
    
    # Whether to display the side menu
    "show_sidebar": True,
    
    # Whether to aut expand the menu
    "navigation_expanded": True,
    
    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": [],
    
    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [],
    
    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    # "order_with_respect_to": ["auth", "books", "books.author", "books.book"],
    
    # Custom links to append to app groups, keyed on app name
    # "custom_links": {
    #     "books": [{
    #         "name": "Make Messages",
    #         "url": "make_messages",
    #         "icon": "fas fa-comments",
    #         "permissions": ["books.view_book"]
    #     }]
    # },
    
    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.5.0,5.6.0,5.6.1,5.6.3,5.7.0,5.7.1,5.7.2,5.8.0,5.8.1,5.8.2,5.9.0,5.10.0,5.10.1,5.10.2,5.11.0,5.11.1,5.11.2,5.12.0,5.12.1,5.13.0,5.13.1,5.14.0,5.15.0,5.15.1,5.15.2,5.15.3,5.15.4,5.16.0,5.16.1,5.17.0,5.18.0,5.18.1,5.18.2,5.18.3,5.19.0 for the full list of 5.19.0 icon classes
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,
    
    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": None,
    "custom_js": None,
    # Whether to link font from fonts.googleapis.com (use custom_css to supply font otherwise)
    "use_google_fonts_cdn": True,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": False,
    
    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    # Add a language dropdown into the admin
    "language_chooser": False,
}

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}


# YASG (Swagger) Configuration
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'JWT Authorization header using the Bearer scheme. Example: "Authorization: Bearer {token}"'
        }
    },
    'USE_SESSION_AUTH': False,
    'JSON_EDITOR': True,
    'SUPPORTED_SUBMIT_METHODS': [
        'get',
        'post',
        'put',
        'delete',
        'patch'
    ],
    'OPERATIONS_SORTER': 'alpha',
    'TAGS_SORTER': 'alpha',
    'DOC_EXPANSION': 'none',
    'DEEP_LINKING': True,
    'SHOW_EXTENSIONS': True,
    'SHOW_COMMON_EXTENSIONS': True,
    'DEFAULT_MODEL_RENDERING': 'model',
    'DEFAULT_FIELD_INSPECTORS': [
        'drf_yasg.inspectors.CamelCaseJSONFilter',
        'drf_yasg.inspectors.InlineSerializerInspector',
        'drf_yasg.inspectors.HiddenFieldInspector',
        'drf_yasg.inspectors.RelatedFieldInspector',
        'drf_yasg.inspectors.ChoiceFieldInspector',
        'drf_yasg.inspectors.FileFieldInspector',
        'drf_yasg.inspectors.DictFieldInspector',
        'drf_yasg.inspectors.SimpleFieldInspector',
        'drf_yasg.inspectors.StringDefaultFieldInspector',
    ],
    'DEFAULT_PAGINATOR_INSPECTORS': [
        'drf_yasg.inspectors.DjangoRestResponsePagination',
        'drf_yasg.inspectors.CoreAPICompatInspector',
    ],
}

REDOC_SETTINGS = {
    'LAZY_RENDERING': False,
    'HIDE_HOSTNAME': False,
    'EXPAND_RESPONSES': 'all',
    'PATH_IN_MIDDLE': True,
}

# Email Configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='WeDesignz <noreply@wedesignz.com>')
ADMIN_EMAIL = config('ADMIN_EMAIL', default='admin@wedesignz.com')

# Email Addresses for different purposes
NO_REPLY_EMAIL = config('NO_REPLY_EMAIL', default='no-reply@wedesignz.com')
INFO_EMAIL = config('INFO_EMAIL', default='info@wedesignz.com')
SUPPORT_EMAIL = config('SUPPORT_EMAIL', default='support@wedesignz.com')

# Site Configuration
SITE_URL = config('SITE_URL', default='http://localhost:8000')

# Razorpay Configuration
RAZORPAY_KEY_ID = config('RAZORPAY_KEY_ID', default='')
RAZORPAY_KEY_SECRET = config('RAZORPAY_KEY_SECRET', default='')
RAZORPAY_WEBHOOK_SECRET = config('RAZORPAY_WEBHOOK_SECRET', default='')

# WhatsApp Business API Configuration
WHATSAPP_PHONE_NUMBER_ID = config('WHATSAPP_PHONE_NUMBER_ID', default='')
WHATSAPP_ACCESS_TOKEN = config('WHATSAPP_ACCESS_TOKEN', default='')
WHATSAPP_OTP_TEMPLATE_NAME = config('WHATSAPP_OTP_TEMPLATE_NAME', default='otp_template')

# Instagram/Facebook Configuration
INSTAGRAM_APP_ID = config('INSTAGRAM_APP_ID', default='')
INSTAGRAM_APP_SECRET = config('INSTAGRAM_APP_SECRET', default='')
INSTAGRAM_ACCESS_TOKEN = config('INSTAGRAM_ACCESS_TOKEN', default='')
INSTAGRAM_REDIRECT_URI = config('INSTAGRAM_REDIRECT_URI', default='')
# Also support FACEBOOK_APP_ID and FACEBOOK_APP_SECRET for compatibility
# If FACEBOOK_APP_ID is not set, fallback to INSTAGRAM_APP_ID
FACEBOOK_APP_ID = config('FACEBOOK_APP_ID', default='') or INSTAGRAM_APP_ID
FACEBOOK_APP_SECRET = config('FACEBOOK_APP_SECRET', default='') or INSTAGRAM_APP_SECRET

# Celery Configuration
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='django-db')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'
CELERY_ENABLE_UTC = True

# Celery Beat Configuration
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Celery Task Settings
CELERY_TASK_ALWAYS_EAGER = config('CELERY_TASK_ALWAYS_EAGER', default=False, cast=bool)
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_SEND_TASK_EVENTS = True
CELERY_TASK_SEND_SENT_EVENT = True

# Celery Monitoring
CELERY_FLOWER_URL = config('CELERY_FLOWER_URL', default='http://localhost:5555')

# Admin Authentication Settings
ENCRYPTION_KEY = config('ENCRYPTION_KEY', default='your-32-character-secret-key-here')
ADMIN_2FA_ISSUER_NAME = config('ADMIN_2FA_ISSUER_NAME', default='WeDesignz Admin')
ADMIN_SESSION_TIMEOUT_HOURS = config('ADMIN_SESSION_TIMEOUT_HOURS', default=24, cast=int)

# Business Configuration
COMMISSION_RATE = config('COMMISSION_RATE', default=10.0, cast=float)
GST_PERCENTAGE = config('GST_PERCENTAGE', default=18.0, cast=float)
CUSTOM_ORDER_TIME_SLOT_HOURS = config('CUSTOM_ORDER_TIME_SLOT_HOURS', default=1, cast=int)
MINIMUM_REQUIRED_DESIGNS_ONBOARD = config('MINIMUM_REQUIRED_DESIGNS_ONBOARD', default=50, cast=int)
FREE_DESIGNS_PER_ACCOUNT_ONE_TIME = config('FREE_DESIGNS_PER_ACCOUNT_ONE_TIME', default=10, cast=int)
FREE_CUSTOM_ORDERS_PER_ACCOUNT = config('FREE_CUSTOM_ORDERS_PER_ACCOUNT', default=2, cast=int)

# PDF Download Configuration - only 20, 50, 100 allowed (values > 100 are filtered out)
_raw_pdf_opts = [int(x.strip()) for x in config('PAID_PDF_DESIGNS_OPTIONS', default='20,50,100').split(',')]
PAID_PDF_DESIGNS_OPTIONS = [x for x in _raw_pdf_opts if x <= 100] or [20, 50, 100]
# Free PDF downloads use the first value of PAID_PDF_DESIGNS_OPTIONS
FREE_PDF_DESIGNS_COUNT = PAID_PDF_DESIGNS_OPTIONS[0] if PAID_PDF_DESIGNS_OPTIONS else 50

# PDF Pricing Configuration
PAID_PDF_PRICE_PER_DESIGN_FIRSTN = config('PAID_PDF_PRICE_PER_DESIGN_FIRSTN', default=2.00, cast=float)
PAID_PDF_PRICE_PER_DESIGN_SELECTED = config('PAID_PDF_PRICE_PER_DESIGN_SELECTED', default=4.00, cast=float)

# CORS Configuration
# Production frontend domains
CORS_ALLOWED_ORIGINS = [
    # Production domains
    "https://wedesignz.com",
    "https://www.wedesignz.com",
    "https://admin.wedesignz.com",
    "https://api.wedesignz.com",
    
    # Development domains
    "https://dev.wedesignz.com",
    "https://dev.admin.wedesignz.com",
    "https://dev.api.wedesignz.com",

    # Local development domains
    "http://localhost:5000",
    "http://127.0.0.1:5000",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5001",
    "http://127.0.0.1:5001",
    "http://localhost:5002",  # WebApp dev server
    "http://127.0.0.1:5002",  # WebApp dev server
]

# Allow CORS from environment variable (comma-separated list)
# This allows adding additional origins via environment variable
# Example: CORS_ADDITIONAL_ORIGINS=https://example.com,https://another.com
CORS_ADDITIONAL_ORIGINS_STR = config('CORS_ADDITIONAL_ORIGINS', default='')
if CORS_ADDITIONAL_ORIGINS_STR:
    CORS_ADDITIONAL_ORIGINS = [origin.strip() for origin in CORS_ADDITIONAL_ORIGINS_STR.split(',') if origin.strip()]
    CORS_ALLOWED_ORIGINS.extend(CORS_ADDITIONAL_ORIGINS)

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Expose headers that JavaScript can access
CORS_EXPOSE_HEADERS = [
    'content-disposition',  # Allow frontend to read filename from Content-Disposition header
    'x-filename',  # Custom header for easier filename access
    'content-type',
    'content-length',
]

# Logging Configuration
# Create logs directory if it doesn't exist (do this before LOGGING config)
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
try:
    if not os.path.exists(LOGS_DIR):
        os.makedirs(LOGS_DIR, mode=0o755)
except (OSError, PermissionError) as e:
    # If we can't create the directory, just log to console
    pass

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'stream': 'ext://sys.stderr',  # Output to stderr so Gunicorn/journalctl can capture it reliably
            'level': 'WARNING',  # Only WARNING+ in terminal (no per-request API logs)
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',  # No terminal output unless WARNING or higher
    },
    'loggers': {
        # Django framework loggers - no terminal output for API (only WARNING+ to console)
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console'],
            'level': 'WARNING',  # Suppress per-request HTTP logs in terminal (still logged to file if enabled)
            'propagate': False,
        },
        'django.utils.autoreload': {
            'handlers': ['console'],
            'level': 'WARNING',  # Hide file change detection logs (unnecessary noise)
            'propagate': False,
        },
        # Third-party loggers
        # Custom app loggers - filter out verbose internal processing logs
        'common': {
            'handlers': ['console'],
            'level': 'WARNING',  # Hide verbose common app logs
            'propagate': False,
        },
        'common.views': {
            'handlers': ['console'],
            'level': 'WARNING',  # Hide verbose view logs
            'propagate': False,
        },
        'common.tasks': {
            'handlers': ['console'],
            'level': 'WARNING',  # Hide verbose task logs
            'propagate': False,
        },
        'common.instagram_service': {
            'handlers': ['console'],
            'level': 'WARNING',  # Hide verbose Instagram service logs
            'propagate': False,
        },
        'CoreAdmin': {
            'handlers': ['console'],
            'level': 'WARNING',  # Hide verbose CoreAdmin logs
            'propagate': False,
        },
        'CoreAdmin.views': {
            'handlers': ['console'],
            'level': 'WARNING',  # Hide verbose view processing logs (keep HTTP logs from django.server)
            'propagate': False,
        },
        'CoreAdmin.models': {
            'handlers': ['console'],
            'level': 'WARNING',  # Hide verbose model logs
            'propagate': False,
        },
        'Catalog': {
            'handlers': ['console'],
            'level': 'WARNING',  # Hide verbose Catalog logs
            'propagate': False,
        },
        'Catalog.views': {
            'handlers': ['console'],
            'level': 'WARNING',  # Hide verbose view processing logs (keep HTTP logs from django.server)
            'propagate': False,
        },
        'Catalog.models': {
            'handlers': ['console'],
            'level': 'WARNING',  # Hide verbose model logs (like design number generation)
            'propagate': False,
        },
        'Feedback': {
            'handlers': ['console'],
            'level': 'WARNING',  # Hide verbose Feedback logs
            'propagate': False,
        },
        'Feedback.views': {
            'handlers': ['console'],
            'level': 'WARNING',  # Hide verbose view processing logs
            'propagate': False,
        },
        'Authentication': {
            'handlers': ['console'],
            'level': 'WARNING',  # Hide verbose Authentication logs
            'propagate': False,
        },
        'Authentication.views': {
            'handlers': ['console'],
            'level': 'WARNING',  # Hide verbose view processing logs
            'propagate': False,
        },
    },
}

# Add file handler only if logs directory exists and is writable
# File handler will log at INFO level (more detailed) while console shows HTTP requests + WARNING+
if os.path.exists(LOGS_DIR) and os.access(LOGS_DIR, os.W_OK):
    LOGGING['handlers']['file'] = {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': os.path.join(LOGS_DIR, 'django.log'),
        'maxBytes': 1024 * 1024 * 10,  # 10 MB
        'backupCount': 5,
        'formatter': 'verbose',
        'level': 'INFO',  # File logs include INFO level for debugging
    }
    # Add file handler to all loggers (file will have INFO, console only WARNING+)
    logger_names = [
        'django', 'django.server', 'django.utils.autoreload',
        'common', 'common.views', 'common.tasks', 'common.instagram_service',
        'CoreAdmin', 'CoreAdmin.views', 'CoreAdmin.models',
        'Catalog', 'Catalog.views', 'Catalog.models',
        'Feedback', 'Feedback.views',
        'Authentication', 'Authentication.views',
    ]
    for logger_name in logger_names:
        if logger_name in LOGGING['loggers']:
            if 'file' not in LOGGING['loggers'][logger_name]['handlers']:
                LOGGING['loggers'][logger_name]['handlers'].append('file')