"""
Django settings for API project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-rfwr9@$tm$bp^-x%v%n$j3dz%)^aenhm%2hl-ds6oifkl2a!+a')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Allowed hosts - includes production API domain and localhost for development
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,devapi.wedesignz.com').split(',')

# CSRF Trusted Origins - origins that are trusted for CSRF checks
# This is needed for cross-origin requests from frontend applications
CSRF_TRUSTED_ORIGINS = [
    # Production domains
    "https://wedesignz.com",
    "https://www.wedesignz.com",
    "https://admin.wedesignz.com",
    
    # Development domains
    "https://webapp.wedesignz.com",
    "https://adminwebapp.wedesignz.com",
    
    # Local development domains
    "http://localhost:5000",
    "http://127.0.0.1:5000",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5001",
    "http://127.0.0.1:5001",
    "http://localhost:5002",
    "http://127.0.0.1:5002",
]

# Allow CSRF trusted origins from environment variable
CSRF_TRUSTED_ORIGINS_STR = config('CSRF_TRUSTED_ORIGINS', default='')
if CSRF_TRUSTED_ORIGINS_STR:
    additional_origins = [origin.strip() for origin in CSRF_TRUSTED_ORIGINS_STR.split(',') if origin.strip()]
    CSRF_TRUSTED_ORIGINS.extend(additional_origins)


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Jazzmin admin theme
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # CORS headers for cross-origin requests
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_yasg',  # Swagger documentation
    
    # Celery apps
    'django_celery_beat',  # Celery Beat for periodic tasks
    'django_celery_results',  # Celery Results backend
    
    # Custom apps
    'common',  # Common utilities, signals, and cron jobs
    'Authentication',
    'CoreAdmin',  # Core Admin Panel
    'AdminAnalytics',  # Admin Analytics and Reports
    'Accounts',
    'Catalog',
    'Coupons',
    'CustomRequests',
    'Feedback',
    'MediaFiles',
    'Orders',
    'Plans',
    'Profiles',
    'Razorpay',
    'Wallet',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware - must be before CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'CoreAdmin.middleware.ModeratorRestrictionMiddleware',
    'CoreAdmin.middleware.AdminActivityLoggingMiddleware',
    'common.error_handler.ErrorHandlerMiddleware',  # Error logging middleware - should be last
]

ROOT_URLCONF = 'API.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'API.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.postgresql'),
        'NAME': config('DB_NAME', default='wedesignz_db'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# Media files configuration
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# For Development
# STATIC_URL = '/static/'
# STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles/')
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# For Production
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# Only include staticfiles directory if it exists
staticfiles_dir = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    staticfiles_dir,
] if os.path.exists(staticfiles_dir) else []
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# File Upload Size Limits (1GB = 1073741824 bytes)
DATA_UPLOAD_MAX_MEMORY_SIZE = 1073741824  # 1GB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # Increase limit for admin list views with many items
FILE_UPLOAD_MAX_MEMORY_SIZE = 1073741824  # 1GB

# Email Configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='')

# Site Domain (for building absolute URLs)
SITE_DOMAIN = config('SITE_DOMAIN', default='wedesignz.com')  # Main website domain (for design links)
MEDIA_DOMAIN = config('MEDIA_DOMAIN', default='devapi.wedesignz.com')  # Media files domain (where images are hosted)
ADMIN_WEBAPP_URL = config('ADMIN_WEBAPP_URL', default='https://admin.wedesignz.com')  # Admin webapp URL (for redirects)

# Pinterest Integration Settings
PINTEREST_APP_ID = config('PINTEREST_APP_ID', default='')
PINTEREST_APP_SECRET = config('PINTEREST_APP_SECRET', default='')
PINTEREST_REDIRECT_URI = config('PINTEREST_REDIRECT_URI', default='https://wedesignz.com/api/pinterest/callback')
PINTEREST_USE_SANDBOX = config('PINTEREST_USE_SANDBOX', default='True', cast=bool)  # Use sandbox for trial access
# Note: Access token and board ID are stored in PinterestIntegration model (database)
# These env vars are fallbacks for initial setup
PINTEREST_ACCESS_TOKEN = config('PINTEREST_ACCESS_TOKEN', default='')
PINTEREST_BOARD_ID = config('PINTEREST_BOARD_ID', default='')
PINTEREST_ENABLED = config('PINTEREST_ENABLED', default='False', cast=bool)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# Jazzmin Configuration
JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "WeDesignz Admin",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "WeDesignz",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "WeDesignz",

    # Logo to use for your site, must be present in static files, used for brand on top left (sidebar after login)
    "site_logo": "Logos/ONLY LOGO.png",

    # Logo to use for your site, must be present in static files, used for login form logo (if site_logo is not set)
    "login_logo": "Logos/WD LOGO2048BLACK.png",

    # Logo to use for login form in dark themes (if login_logo is not set)
    "login_logo_dark": "Logos/WD LOGO2048BLACK.png",

    # CSS classes that are applied to the logo above
    "site_logo_classes": "",

    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": "favicon/favicon-96x96.png",

    # Welcome text on the login screen
    "welcome_sign": "Welcome to WeDesignz Admin Panel",

    # Copyright on the footer
    "copyright": "WeDesignz",

    # List of model admins to search from the search bar, search bar omitted if empty
    # Temporarily disabled to debug white screen issue
    "search_model": [],

    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
    "user_avatar": None,

    ############
    # Top Menu #
    ############

    # Links to put along the top menu
    "topmenu_links": [
        # Url that gets reversed (Permissions can be added)
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        # external url that opens in a new window (Permissions can be added)
        {"name": "Support", "url": "https://github.com/WeDesignz/API", "new_window": True},
        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},
    ],

    #############
    # User Menu #
    #############

    # Additional links to include in the user menu on the top right ("app" url type is not supported)
    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/WeDesignz/API", "new_window": True},
        {"model": "auth.user"}
    ],

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": True,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": [],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [],

    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": ["auth", "Accounts", "Catalog", "Orders", "Profiles", "Wallet", "Plans", "Coupons", "CustomRequests", "Feedback", "Razorpay", "MediaFiles"],

    # Custom links to append to app groups, keyed on app name
    "custom_links": {
        "Accounts": [{
            "name": "User Management",
            "url": "admin:auth_user_changelist",
            "icon": "fas fa-users",
            "permissions": ["auth.view_user"]
        }],
        "Catalog": [{
            "name": "Product Analytics",
            "url": "admin:catalog_product_changelist",
            "icon": "fas fa-chart-bar",
            "permissions": ["catalog.view_product"]
        }],
        "Orders": [{
            "name": "Order Analytics",
            "url": "admin:orders_order_changelist",
            "icon": "fas fa-shopping-cart",
            "permissions": ["orders.view_order"]
        }],
    },

    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free
    # for the full list of 5.13.0 free icon classes
    "icons": {
        # Authentication & User Management
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        
        # Accounts App
        "accounts": "fas fa-user-shield",
        "accounts.Email": "fas fa-envelope",
        "accounts.MobileNumber": "fas fa-phone",
        "accounts.OTP": "fas fa-key",
        "accounts.Role": "fas fa-user-tag",
        "accounts.Permission": "fas fa-lock",
        "accounts.PermissionHasRole": "fas fa-link",
        
        # Authentication App
        "authentication": "fas fa-fingerprint",
        "authentication.Email": "fas fa-envelope-open",
        "authentication.MobileNumber": "fas fa-mobile-alt",
        "authentication.OTP": "fas fa-shield-alt",
        "authentication.User": "fas fa-user-check",
        
        # Catalog App
        "catalog": "fas fa-store",
        "catalog.Category": "fas fa-tags",
        "catalog.Product": "fas fa-box",
        "catalog.ProductCounter": "fas fa-chart-line",
        "catalog.CollectionBundle": "fas fa-layer-group",
        "catalog.Tags": "fas fa-tag",
        
        # Coupons App
        "coupons": "fas fa-percentage",
        "coupons.Coupon": "fas fa-ticket-alt",
        "coupons.CouponUsage": "fas fa-receipt",
        
        # Custom Requests App
        "custom_requests": "fas fa-clipboard-check",
        "custom_requests.CustomOrderRequest": "fas fa-clipboard-list",
        
        # Feedback App
        "feedback": "fas fa-comments",
        "feedback.FeedbackQuestion": "fas fa-question-circle",
        "feedback.FeedbackReview": "fas fa-star",
        "feedback.ReportIssue": "fas fa-exclamation-triangle",
        
        # Media Files App
        "mediafiles": "fas fa-images",
        "mediafiles.Media": "fas fa-image",
        "mediafiles.Relation": "fas fa-link",
        
        # Orders App
        "orders": "fas fa-shopping-bag",
        "orders.Cart": "fas fa-shopping-cart",
        "orders.Order": "fas fa-shopping-bag",
        "orders.OrderTransaction": "fas fa-receipt",
        
        # Plans App
        "plans": "fas fa-crown",
        "plans.Plan": "fas fa-crown",
        "plans.Subscription": "fas fa-calendar-check",
        
        # Profiles App
        "profiles": "fas fa-user-circle",
        "profiles.Addresses": "fas fa-map-marker-alt",
        "profiles.DesignerProfile": "fas fa-palette",
        "profiles.Studio": "fas fa-building",
        "profiles.StudioBusinessDetails": "fas fa-briefcase",
        "profiles.StudioMember": "fas fa-users",
        "profiles.Ratings": "fas fa-star-half-alt",
        
        # Razorpay App
        "razorpay": "fas fa-credit-card",
        "razorpay.RazorpayPayment": "fas fa-credit-card",
        "razorpay.RazorpayWebhookEvent": "fas fa-plug",
        
        # Wallet App
        "wallet": "fas fa-wallet",
        "wallet.Wallet": "fas fa-wallet",
        "wallet.WalletTransaction": "fas fa-exchange-alt",
        "wallet.WalletWithdrawalRequest": "fas fa-money-bill-wave",
        
        # Celery & Background Tasks
        "django_celery_beat": "fas fa-clock",
        "django_celery_beat.PeriodicTask": "fas fa-tasks",
        "django_celery_beat.IntervalSchedule": "fas fa-stopwatch",
        "django_celery_beat.CrontabSchedule": "fas fa-calendar-alt",
        "django_celery_beat.SolarSchedule": "fas fa-sun",
        "django_celery_beat.ClockedSchedule": "fas fa-bell",
        
        # Celery Results
        "django_celery_results": "fas fa-chart-pie",
        "django_celery_results.TaskResult": "fas fa-check-circle",
    },
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,

    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": "custom/admin-fix.css",
    "custom_js": None,
    # Whether to link font from fonts.googleapis.com (use custom_css to supply font otherwise)
    "use_google_fonts_cdn": True,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": False,

    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    # Add a language dropdown into the admin
    "language_chooser": False,
}

# YASG (Swagger) Configuration
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'JWT Authorization header using the Bearer scheme. Example: "Authorization: Bearer {token}"'
        }
    },
    'USE_SESSION_AUTH': False,
    'JSON_EDITOR': True,
    'SUPPORTED_SUBMIT_METHODS': [
        'get',
        'post',
        'put',
        'delete',
        'patch'
    ],
    'OPERATIONS_SORTER': 'alpha',
    'TAGS_SORTER': 'alpha',
    'DOC_EXPANSION': 'none',
    'DEEP_LINKING': True,
    'SHOW_EXTENSIONS': True,
    'SHOW_COMMON_EXTENSIONS': True,
    'DEFAULT_MODEL_RENDERING': 'model',
    'DEFAULT_FIELD_INSPECTORS': [
        'drf_yasg.inspectors.CamelCaseJSONFilter',
        'drf_yasg.inspectors.InlineSerializerInspector',
        'drf_yasg.inspectors.HiddenFieldInspector',
        'drf_yasg.inspectors.RelatedFieldInspector',
        'drf_yasg.inspectors.ChoiceFieldInspector',
        'drf_yasg.inspectors.FileFieldInspector',
        'drf_yasg.inspectors.DictFieldInspector',
        'drf_yasg.inspectors.SimpleFieldInspector',
        'drf_yasg.inspectors.StringDefaultFieldInspector',
    ],
    'DEFAULT_PAGINATOR_INSPECTORS': [
        'drf_yasg.inspectors.DjangoRestResponsePagination',
        'drf_yasg.inspectors.CoreAPICompatInspector',
    ],
}

REDOC_SETTINGS = {
    'LAZY_RENDERING': False,
    'HIDE_HOSTNAME': False,
    'EXPAND_RESPONSES': 'all',
    'PATH_IN_MIDDLE': True,
}

# Email Configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='WeDesignz <noreply@wedesignz.com>')
ADMIN_EMAIL = config('ADMIN_EMAIL', default='admin@wedesignz.com')

# Email Addresses for different purposes
NO_REPLY_EMAIL = config('NO_REPLY_EMAIL', default='no-reply@wedesignz.com')
INFO_EMAIL = config('INFO_EMAIL', default='info@wedesignz.com')
SUPPORT_EMAIL = config('SUPPORT_EMAIL', default='support@wedesignz.com')

# Site Configuration
SITE_URL = config('SITE_URL', default='http://localhost:8000')

# Razorpay Configuration
RAZORPAY_KEY_ID = config('RAZORPAY_KEY_ID', default='')
RAZORPAY_KEY_SECRET = config('RAZORPAY_KEY_SECRET', default='')
RAZORPAY_WEBHOOK_SECRET = config('RAZORPAY_WEBHOOK_SECRET', default='')

# WhatsApp Business API Configuration
WHATSAPP_PHONE_NUMBER_ID = config('WHATSAPP_PHONE_NUMBER_ID', default='')
WHATSAPP_ACCESS_TOKEN = config('WHATSAPP_ACCESS_TOKEN', default='')
WHATSAPP_OTP_TEMPLATE_NAME = config('WHATSAPP_OTP_TEMPLATE_NAME', default='otp_template')

# Instagram/Facebook Configuration
INSTAGRAM_APP_ID = config('INSTAGRAM_APP_ID', default='')
INSTAGRAM_APP_SECRET = config('INSTAGRAM_APP_SECRET', default='')
INSTAGRAM_ACCESS_TOKEN = config('INSTAGRAM_ACCESS_TOKEN', default='')
INSTAGRAM_REDIRECT_URI = config('INSTAGRAM_REDIRECT_URI', default='')
# Also support FACEBOOK_APP_ID and FACEBOOK_APP_SECRET for compatibility
# If FACEBOOK_APP_ID is not set, fallback to INSTAGRAM_APP_ID
FACEBOOK_APP_ID = config('FACEBOOK_APP_ID', default='') or INSTAGRAM_APP_ID
FACEBOOK_APP_SECRET = config('FACEBOOK_APP_SECRET', default='') or INSTAGRAM_APP_SECRET

# Celery Configuration
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='django-db')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'
CELERY_ENABLE_UTC = True

# Celery Beat Configuration
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Celery Task Settings
CELERY_TASK_ALWAYS_EAGER = config('CELERY_TASK_ALWAYS_EAGER', default=False, cast=bool)
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_SEND_TASK_EVENTS = True
CELERY_TASK_SEND_SENT_EVENT = True

# Celery Monitoring
CELERY_FLOWER_URL = config('CELERY_FLOWER_URL', default='http://localhost:5555')

# Admin Authentication Settings
ENCRYPTION_KEY = config('ENCRYPTION_KEY', default='your-32-character-secret-key-here')
ADMIN_2FA_ISSUER_NAME = config('ADMIN_2FA_ISSUER_NAME', default='WeDesignz Admin')
ADMIN_SESSION_TIMEOUT_HOURS = config('ADMIN_SESSION_TIMEOUT_HOURS', default=24, cast=int)

# Business Configuration
COMMISSION_RATE = config('COMMISSION_RATE', default=10.0, cast=float)
GST_PERCENTAGE = config('GST_PERCENTAGE', default=18.0, cast=float)
CUSTOM_ORDER_TIME_SLOT_HOURS = config('CUSTOM_ORDER_TIME_SLOT_HOURS', default=1, cast=int)
MINIMUM_REQUIRED_DESIGNS_ONBOARD = config('MINIMUM_REQUIRED_DESIGNS_ONBOARD', default=50, cast=int)

# PDF Download Configuration
PAID_PDF_DESIGNS_OPTIONS = [int(x.strip()) for x in config('PAID_PDF_DESIGNS_OPTIONS', default='50,100,200,300,400,500').split(',')]
# Free PDF downloads use the first value of PAID_PDF_DESIGNS_OPTIONS
FREE_PDF_DESIGNS_COUNT = PAID_PDF_DESIGNS_OPTIONS[0] if PAID_PDF_DESIGNS_OPTIONS else 50

# PDF Pricing Configuration
PAID_PDF_PRICE_PER_DESIGN_FIRSTN = config('PAID_PDF_PRICE_PER_DESIGN_FIRSTN', default=2.00, cast=float)
PAID_PDF_PRICE_PER_DESIGN_SELECTED = config('PAID_PDF_PRICE_PER_DESIGN_SELECTED', default=4.00, cast=float)

# CORS Configuration
# Production frontend domains
CORS_ALLOWED_ORIGINS = [
    # Production domains
    "https://wedesignz.com",
    "https://www.wedesignz.com",
    "https://admin.wedesignz.com",
    "https://api.wedesignz.com",
    
    # Development domains
    "https://dev.wedesignz.com",
    "https://dev.admin.wedesignz.com",
    "https://dev.api.wedesignz.com",

    # Local development domains
    "http://localhost:5000",
    "http://127.0.0.1:5000",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5001",
    "http://127.0.0.1:5001",
    "http://localhost:5002",  # WebApp dev server
    "http://127.0.0.1:5002",  # WebApp dev server
]

# Allow CORS from environment variable (comma-separated list)
# This allows adding additional origins via environment variable
# Example: CORS_ADDITIONAL_ORIGINS=https://example.com,https://another.com
CORS_ADDITIONAL_ORIGINS_STR = config('CORS_ADDITIONAL_ORIGINS', default='')
if CORS_ADDITIONAL_ORIGINS_STR:
    CORS_ADDITIONAL_ORIGINS = [origin.strip() for origin in CORS_ADDITIONAL_ORIGINS_STR.split(',') if origin.strip()]
    CORS_ALLOWED_ORIGINS.extend(CORS_ADDITIONAL_ORIGINS)

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Logging Configuration
# Create logs directory if it doesn't exist (do this before LOGGING config)
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
try:
    if not os.path.exists(LOGS_DIR):
        os.makedirs(LOGS_DIR, mode=0o755)
except (OSError, PermissionError) as e:
    # If we can't create the directory, just log to console
    pass

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'stream': 'ext://sys.stderr',  # Output to stderr so Gunicorn/journalctl can capture it reliably
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',  # Show INFO and above in console
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'common': {
            'handlers': ['console'],
            'level': 'INFO',  # Show INFO level logs for common app
            'propagate': False,
        },
        'common.views': {
            'handlers': ['console'],
            'level': 'INFO',  # Show INFO level logs for views
            'propagate': False,
        },
        'common.tasks': {
            'handlers': ['console'],
            'level': 'INFO',  # Show INFO level logs for tasks
            'propagate': False,
        },
        'common.instagram_service': {
            'handlers': ['console'],
            'level': 'INFO',  # Show INFO level logs for Instagram service
            'propagate': False,
        },
    },
}

# Add file handler only if logs directory exists and is writable
if os.path.exists(LOGS_DIR) and os.access(LOGS_DIR, os.W_OK):
    LOGGING['handlers']['file'] = {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': os.path.join(LOGS_DIR, 'django.log'),
        'maxBytes': 1024 * 1024 * 10,  # 10 MB
        'backupCount': 5,
        'formatter': 'verbose',
    }
    # Add file handler to all loggers
    for logger_name in ['django', 'common', 'common.views', 'common.tasks', 'common.instagram_service']:
        if 'file' not in LOGGING['loggers'][logger_name]['handlers']:
            LOGGING['loggers'][logger_name]['handlers'].append('file')